workflows:
  ios-godot-build-only:
    name: iOS Godot 4.6.1 > Build IPA (WebView injected, no upload)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - ICEFISH

      vars:
        GODOT_VERSION: "4.6.1-stable"
        GODOT_TEMPL_VERSION_DIR: "4.6.1.stable"
        EXPORT_PRESET: "iOS"

      # Оставляем как у тебя: сборка под App Store всё равно требует профили/серты
      ios_signing:
        provisioning_profiles:
          - ICEFISH_APPSTORE_PROFILE

    scripts:
      - name: Install dependencies
        script: |
          set -e
          brew install curl unzip || true
          # ruby уже есть, ставим gem для правки Xcode-проекта
          sudo gem install xcodeproj -N

      - name: Download Godot
        script: |
          set -e
          mkdir -p tools
          cd tools

          curl -L -o godot.zip \
            https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_macos.universal.zip

          unzip -o godot.zip
          chmod +x Godot*.app/Contents/MacOS/Godot*

      - name: Install export templates
        script: |
          set -e
          cd tools

          curl -L -o templates.tpz \
            https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz

          TEMPL_DIR="$HOME/Library/Application Support/Godot/export_templates/${GODOT_TEMPL_VERSION_DIR}"
          mkdir -p "$TEMPL_DIR"

          unzip -o templates.tpz
          mv templates/* "$TEMPL_DIR/"

      - name: Export iOS project
        script: |
          set -e
          mkdir -p build/ios

          GODOT_BIN=$(find tools -type f -path "*Godot*.app/Contents/MacOS/*" | head -n 1)

          "$GODOT_BIN" --headless \
            --path . \
            --export-release "${EXPORT_PRESET}" \
            build/ios

      - name: Inject WebViewManager.swift into exported Xcode project (and link WebKit)
        script: |
          set -e

          XCODEPROJ=$(find build -name "*.xcodeproj" | head -n 1)
          if [ -z "$XCODEPROJ" ]; then
            echo "ERROR: .xcodeproj not found in $IOS_EXPORT_DIR"
            exit 1
          fi
          echo "Using project: $XCODEPROJ"

          # Находим scheme (обычно совпадает с названием таргета)
          SCHEME=$(xcodebuild -list -project "$XCODEPROJ" \
            | awk '/Schemes:/{flag=1;next} flag && NF{print; exit}' \
            | xargs)
          echo "Using scheme: $SCHEME"

          IOS_PROJ_ROOT=$(dirname "$XCODEPROJ")
          echo "iOS project root: $IOS_PROJ_ROOT"

          # Обычно Godot кладёт исходники в папку с именем таргета/схемы
          TARGET_SRC_DIR=$(find "$IOS_PROJ_ROOT" -maxdepth 2 -type d -name "$SCHEME" | head -n 1 || true)
          if [ -z "$TARGET_SRC_DIR" ]; then
            # fallback: если структуры нет, кладём в корень рядом с pbxproj
            TARGET_SRC_DIR="$IOS_PROJ_ROOT"
          fi
          echo "Target source dir: $TARGET_SRC_DIR"

          # 1) Копируем твой Swift
          if [ ! -f "ios/plugins/webview/WebViewManager.swift" ]; then
            echo "ERROR: ios/plugins/webview/WebViewManager.swift not found in repo"
            exit 1
          fi
          cp -v "ios/plugins/webview/WebViewManager.swift" "$TARGET_SRC_DIR/WebViewManager.swift"

          # 2) Правим Xcode project: добавляем WebViewManager.swift в Compile Sources + линкуем WebKit
          cat > /tmp/inject_webview.rb <<'RUBY'
          require 'xcodeproj'

          xcodeproj_path = ENV['XCODEPROJ']
          scheme = ENV['SCHEME']
          target_src_dir = ENV['TARGET_SRC_DIR']

          project = Xcodeproj::Project.open(xcodeproj_path)

          # Находим target по имени scheme, иначе берём первый application target
          target = project.targets.find { |t| t.name == scheme } ||
                   project.targets.find { |t| t.product_type&.include?('application') } ||
                   project.targets.first

          unless target
            puts "ERROR: target not found"
            exit 1
          end

          puts "Using target: #{target.name}"

          # --- Add Swift file to project & build phase
          swift_rel_path = 'WebViewManager.swift'

          # file reference (relative path inside project)
          # Добавляем в main group (без фанатизма)
          main_group = project.main_group

          existing_ref = project.files.find { |f| f.path == swift_rel_path }
          file_ref = existing_ref || project.main_group.new_file(swift_rel_path)

          sources_phase = target.source_build_phase
          already_in_sources = sources_phase.files_references.include?(file_ref)
          unless already_in_sources
            sources_phase.add_file_reference(file_ref, true)
            puts "Added WebViewManager.swift to Compile Sources"
          else
            puts "WebViewManager.swift already in Compile Sources"
          end

          # --- Link WebKit.framework
          frameworks_group = project.frameworks_group

          webkit_ref = project.files.find { |f| f.path == 'System/Library/Frameworks/WebKit.framework' } ||
                       frameworks_group.new_file('System/Library/Frameworks/WebKit.framework')

          frameworks_phase = target.frameworks_build_phase
          unless frameworks_phase.files_references.include?(webkit_ref)
            frameworks_phase.add_file_reference(webkit_ref, true)
            puts "Linked WebKit.framework"
          else
            puts "WebKit.framework already linked"
          end

          # --- Ensure Swift settings (обычно не надо, но пусть будет)
          target.build_configurations.each do |cfg|
            cfg.build_settings['SWIFT_VERSION'] ||= '5.0'
          end

          project.save
          puts "Xcode project saved"
          RUBY

          export XCODEPROJ="$XCODEPROJ"
          export SCHEME="$SCHEME"
          export TARGET_SRC_DIR="$TARGET_SRC_DIR"
          ruby /tmp/inject_webview.rb

      - name: Build IPA
        script: |
          set -e

          XCODEPROJ=$(find build -name "*.xcodeproj" | head -n 1)
          echo "Using project: $XCODEPROJ"

          SCHEME=$(xcodebuild -list -project "$XCODEPROJ" \
            | awk '/Schemes:/{flag=1;next} flag && NF{print; exit}' \
            | xargs)

          echo "Using scheme: $SCHEME"

          xcode-project use-profiles --project "$XCODEPROJ"

          xcodebuild \
            -project "$XCODEPROJ" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            archive

          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.cerentaner.icefishadventure</key>
                  <string>IceFishProfile</string>
              </dict>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath ipa \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - ipa/*.ipa
